## Import data

In [211]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

heart = pd.read_csv("heart.csv")
heart.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

## Encoding categorical variables

Encoding can be done before splitting the data, as it does not create data leakage.

### Encoding gender

- Male = 0
- Female = 1

In [212]:
heart["Sex"] = heart["Sex"].map({"M":0, "F":1})
heart["Sex"].head()

0    0
1    1
2    0
3    1
4    0
Name: Sex, dtype: int64

### Encoding ChestPainType

- TA - 0
- ATA - 1
- ASY - 2
- NAP - 3

In [213]:
heart["ChestPainType"] = heart["ChestPainType"].map({"TA":0, "ATA":1, "ASY":2, "NAP":3})
heart["ChestPainType"].head()

0    1
1    3
2    1
3    2
4    3
Name: ChestPainType, dtype: int64

### Encoding RestingECG

- Normal - 0 
- ST - 1
- LVH - 2

In [ ]:
heart["RestingECG"] = heart["RestingECG"].map({"Normal":0, "ST":1, "LVH":2})
heart["RestingECG"].head()

0    0
1    0
2    1
3    0
4    0
Name: RestingECG, dtype: int64

### Encoding ExerciseAngina

- N - 0
- Y - 1

In [215]:
heart["ExerciseAngina"] = heart["ExerciseAngina"].map({"N":0, "Y":1})
heart["ExerciseAngina"].head()

0    0
1    0
2    0
3    1
4    0
Name: ExerciseAngina, dtype: int64

### Encoding ST_Slope

- Up - 0  
- Flat - 1  
- Down - 2

In [216]:
heart["ST_Slope"] = heart["ST_Slope"].map({"Up":0, "Flat":1, "Down":2})
heart["ST_Slope"].head()

heart.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,1,140,289,0,0,172,0,0.0,0,0
1,49,1,3,160,180,0,0,156,0,1.0,1,1
2,37,0,1,130,283,0,1,98,0,0.0,0,0
3,48,1,2,138,214,0,0,108,1,1.5,1,1
4,54,0,3,150,195,0,0,122,0,0.0,0,0

All categorical variables were encoded and turned into numbers.

## Separating feature from the target

In [217]:
X = heart.drop("HeartDisease", axis = 1)
y = heart["HeartDisease"]

## Splitting into train set and test set

In [218]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size = 0.25)

print("Training X:")
X_train.head()

Training X:

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
279,54,1,1,130,253,0,1,155,0,0.0,0
451,64,0,2,144,0,0,1,122,1,1.0,1
39,48,1,2,150,227,0,0,130,1,1.0,1
557,56,0,3,137,208,1,1,122,1,1.8,1
548,66,0,2,112,261,0,0,140,0,1.5,0

In [219]:
print("Testing X:")
X_test.head()

Testing X:

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
306,55,0,2,115,0,1,0,155,0,0.1,1
711,66,0,2,120,302,0,3,151,0,0.4,1
298,51,0,2,110,0,1,0,92,0,0.0,1
466,55,0,3,120,0,0,1,125,1,2.5,1
253,62,0,1,140,271,0,0,152,0,1.0,0

In [220]:
print("Training y:")
y_train.head()

Training y:

279    0
451    1
39     0
557    1
548    1
Name: HeartDisease, dtype: int64

In [221]:
print("Testing y:")
y_test.head()

Testing y:

306    1
711    0
298    1
466    1
253    0
Name: HeartDisease, dtype: int64

## Removing missing values

### Cholesterol

In [222]:
print("Quantity of missing values in X_train before replacement: ", (X_train["Cholesterol"] == 0).sum())
print("Quantity of missing values in X_test before replacement: ", (X_test["Cholesterol"] == 0).sum())

median_cholesterol = X_train.loc[X_train["Cholesterol"] != 0, "Cholesterol"].median()

X_train["Cholesterol"] = X_train["Cholesterol"].replace(0, median_cholesterol)
X_test["Cholesterol"] = X_test["Cholesterol"].replace(0, median_cholesterol)

Quantity of missing values in X_train before replacement:  119
Quantity of missing values in X_test before replacement:  53

In [223]:
print("Quantity of missing values in X_train after replacement: ", (X_train["Cholesterol"] == 0).sum())
X_train["Cholesterol"].head()

Quantity of missing values in X_train after replacement:  0

279    253
451    236
39     227
557    208
548    261
Name: Cholesterol, dtype: int64

In [224]:
print("Quantity of missing values in X_test after replacement: ", (X_test["Cholesterol"] == 0).sum())
X_test["Cholesterol"].head()

Quantity of missing values in X_test after replacement:  0

306    236
711    302
298    236
466    236
253    271
Name: Cholesterol, dtype: int64

### RestingBP

In [ ]:
print("Quantity of missing values in X_train before deletion: ", (X_train["RestingBP"] == 0).sum())
print("Quantity of missing values in X_test before deletion: ", (X_test["RestingBP"] == 0).sum())

index_missing = X_train[X_train["RestingBP"] == 0].index
X_train = X_train.drop(index = index_missing)
y_train = y_train.drop(index = index_missing)

print("")
print("Quantity of missing values in X_train after deletion: ", (X_train["RestingBP"] == 0).sum())

Quantity of missing values in X_train before deletion:  1
Quantity of missing values in X_test before deletion:  0

Quantity of missing values in X_train after deletion:  0

## Scaling numerical variables

In [226]:
columns = ["Age", "RestingBP", "Cholesterol", "MaxHR", "Oldpeak"]
scale = StandardScaler()
X_train[columns] = scale.fit_transform(X_train[columns])
X_test[columns] = scale.transform(X_test[columns])

In [227]:
X_train[columns].head()

          Age  RestingBP  Cholesterol     MaxHR   Oldpeak
279  0.048737  -0.146525     0.213970  0.704807 -0.838566
451  1.111663   0.631650    -0.107895 -0.601388  0.112871
39  -0.589019   0.965153    -0.278293 -0.284734  0.112871
557  0.261322   0.242563    -0.638025 -0.601388  0.874020
548  1.324248  -1.147035     0.365436  0.111082  0.588589

In [228]:
X_test[columns].head()

          Age  RestingBP  Cholesterol     MaxHR   Oldpeak
306  0.155029  -0.980283    -0.107895  0.704807 -0.743423
711  1.324248  -0.702364     1.141698  0.546480 -0.457991
298 -0.270141  -1.258203    -0.107895 -1.788837 -0.838566
466  0.155029  -0.702364    -0.107895 -0.482643  1.540026
253  0.899078   0.409314     0.554768  0.586062  0.112871

## Result

In [229]:
X_test.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
306,0.155029,0,2,-0.980283,-0.107895,1,0,0.704807,0,-0.743423,1
711,1.324248,0,2,-0.702364,1.141698,0,3,0.546480,0,-0.457991,1
298,-0.270141,0,2,-1.258203,-0.107895,1,0,-1.788837,0,-0.838566,1
466,0.155029,0,3,-0.702364,-0.107895,0,1,-0.482643,1,1.540026,1
253,0.899078,0,1,0.409314,0.554768,0,0,0.586062,0,0.112871,0